#!/usr/bin/env python

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
import os
import glob
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

### POPULATION REFERENCE FILE

#data_tsv="/home/hayabusa/PROJECT_MPN/MPN_DERIVATIVES/MPN_MRIQC/group_bold_MPN.tsv"

data_tsv="/home/hayabusa/PROJECT_MPN/MPN_DERIVATIVES/MPN_MRIQC/MRIQC_MPN_LARGEPOPULATION_REPORTS/group_bold_ses-MPN1Scan1__task-rest.tsv"
df = pd.read_csv(data_tsv, sep='\\t', index_col=0)

# 2. Filter rows using wildcards (regex)
# '^Gene_.*' matches rows starting with 'Gene_'
filtered_df = df.filter(regex='^.*ses-MPN1Scan1_task-rest.*echo-1_bold', axis=0)
features = filtered_df.drop(columns=['bids_name','gcor','aqi','aor'], errors='ignore')


features = features.select_dtypes(include=[np.number]).dropna(axis=1)

# 3. Standardize the features (Crucial for PCA)
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

# 4. Fit PCA
pca = PCA(n_components=4) # Inspect the top 5 principal components
principal_components = pca.fit_transform(scaled_features)
pca_df = pd.DataFrame(data=principal_components, columns=["PC1", "PC2","PC3", "PC4"])

# 5. Extract feature loadings to see which IQMs characterize each component
loadings = pd.DataFrame(
    pca.components_.T, 
    columns=[f'PC{i+1}' for i in range(4)], 
    index=features.columns
)



modality='BOLD'
# 6. Display top 5 metrics characterizing PC1, PC2, PC3
print(f"--- Top features for {modality} PC1 ---")
print(loadings['PC1'].abs().sort_values(ascending=False).head(4))

print(f"\n--- Top features for {modality} PC2 ---")
print(loadings['PC2'].abs().sort_values(ascending=False).head(4))

print(f"--- Top features for {modality} PC3 ---")
print(loadings['PC3'].abs().sort_values(ascending=False).head(4))

print(f"\n--- Top features for {modality} PC4 ---")
print(loadings['PC4'].abs().sort_values(ascending=False).head(4))

# 7. Print explained variance
print(f"\nExplained variance per component: {pca.explained_variance_ratio_}") # PC1-3 explain ~60% variance
# First 2 components explained variance
print(f"\nExplained variance for PC1 and PC2: {pca.explained_variance_ratio_[0]+pca.explained_variance_ratio_[1]}") 



# 5. Plot the first two principal components
plt.figure(figsize=(8, 6))
plt.scatter(pca_df["PC1"], pca_df["PC2"], alpha=0.7, linewidth=0.5)
# Add labels and variance explanation ratios
exp_var = pca.explained_variance_ratio_ * 100
plt.xlabel(f"Principal Component 1 ({exp_var[0]:.2f}% Variance)")
plt.ylabel(f"Principal Component 2 ({exp_var[1]:.2f}% Variance)")
plt.title("PCA of MRIQC Image Quality Metrics (IQMs)")
plt.grid(True, linestyle="--", alpha=0.5)
plt.show()

# 5. Plot the 3rd and 4th components
plt.figure(figsize=(8, 6))
plt.scatter(pca_df["PC3"], pca_df["PC4"], alpha=0.7, linewidth=0.5)
# Add labels and variance explanation ratios
exp_var = pca.explained_variance_ratio_ * 100
plt.xlabel(f"Principal Component 3 ({exp_var[2]:.2f}% Variance)")
plt.ylabel(f"Principal Component 4 ({exp_var[3]:.2f}% Variance)")
plt.title("PCA of MRIQC Image Quality Metrics (IQMs)")
plt.grid(True, linestyle="--", alpha=0.5)
plt.show()


# 5. Plot the scree plot
plt.figure(figsize=(8, 5))
plt.plot(
    range(1, len(exp_var) + 1),
    exp_var,
    "o-",
    linewidth=2,
    color="b",
)
plt.title("Scree Plot of MRIqc IQMs")
plt.xlabel("Principal Component")
plt.ylabel("Explained Variance (%)")
plt.grid(True)
plt.show()


###

filtered_df = filtered_df.transpose()
filtered_df.index.name = 'IQM'

# 4. Melt to long-form (necessary for Seaborn)  ### Not correct... we need many vars per row?? ###
df_melted = filtered_df.reset_index().melt(id_vars=['IQM'], var_name='Bids_name', value_name='Value')

# Filter 2nd time now for IQM of interest

variables = ['snr','tsnr', 'dvars_std','efc','fwhm_avg']
FDF = df_melted[df_melted["IQM"].isin(variables)]


#### PARTICIPANT FILE (json) # ability of combining runs etc

data="/home/hayabusa/PROJECT_MPN/MPN_DERIVATIVES/MPN_MRIQC/sub-MPN0000106*/*/ses-MPN1Scan1/func/*_ses-MPN1Scan1_task-present*_bold.json"
file_list  = glob.glob(data)
variables = ['snr','tsnr', 'dvars_std','efc','fd_mean']
data_list = []

# 2. Loop through files with validation
for file in file_list:
    try:
        with open(file, 'r') as f:
            data = json.load(f)
            # Ensure data is not empty and is a dictionary/list
            if not data:
                print(f"Skipping empty file: {file}")
                continue
            # Need to remove problematic fields
            keys_to_remove = ["aor", "aqi","bids_meta","gcor","provenance"]
            for key in keys_to_remove:
                data.pop(key, None)
            # Assuming JSON structure: {"variable1": [...], "variable2": [...]}
            df_temp = pd.DataFrame([data]) # wrap dictionary into a list
            df_temp['source'] = file # Label data source
            data_list.append(df_temp)
            
    except (json.JSONDecodeError, OSError) as e:
        print(f"Skipping invalid/missing JSON file {file}: {e}")
        continue
     
df_all = pd.concat(data_list, ignore_index=True)
df_melted_SINGLE = df_all.melt(id_vars=['source'], value_vars=variables, 
                            var_name='IQM', value_name='Value')



# ############################# #
# Plot population violin plots

fig, axes = plt.subplots(len(variables), 1, figsize=(10, 5 * len(variables)))
sns.set(font_scale=1.5)
for i, var in enumerate(variables):

      # POP
      
      subset = df_melted[df_melted['IQM'] == var]
      sns.violinplot(data=subset, x='Value', y='IQM',fill=True, ax=axes[i], color="skyblue")
      sns.boxplot(data=subset, x='Value', y='IQM',fill=True, linewidth=1.5, linecolor="red", medianprops={"color": "r", "linewidth": 2},boxprops={"facecolor": "pink","linewidth": 1.5}, flierprops={"marker": "x", "markerfacecolor": "r", "linewidth": 2},  ax=axes[i])
      sns.stripplot(data=subset, x='Value', y='IQM',linewidth=1.5, color="red", edgecolor="r",  ax=axes[i])
      
      
       # Quantify OUtliers and print %
      # 2. Calculate IQR (Interquartile Range)
      q1 = subset["Value"].quantile(0.25)
      q3 = subset["Value"].quantile(0.75)
      iqr = q3 - q1

      # 3. Define outlier boundaries
      lower_bound = q1 - 1.5 * iqr
      upper_bound = q3 + 1.5 * iqr

      # 4. Identify outliers
      outliers = subset[(subset["Value"]< lower_bound) | (subset["Value"] > upper_bound)]

      # 5. Quantify the percentage
      total_points = len(subset["Value"])
      num_outliers = len(outliers)
      percentage_outliers = (num_outliers / total_points) * 100

      print(f"Total Data Points in {var}: {total_points}")
      print(f"Number of Outliers in {var}: {num_outliers}")
      print(f"Percentage of Outliers in {var}: {percentage_outliers:.2f}%")
      
      # Apply the flag per category group
      sns.stripplot(data=outliers, x='Value', y='IQM',linewidth=1.5, color="yellow", edgecolor="y",  ax=axes[i])

      
      # SINGLE
      subset2 = df_melted_SINGLE[df_melted_SINGLE['IQM'] == var]
      sns.stripplot(data=subset2, x='Value', y='IQM',linewidth=3.5, color="green", edgecolor="green",  ax=axes[i])
      axes[i].set_title(f'Distribution of {var}')
      axes[i].set_xticklabels(axes[i].get_xticklabels(),rotation=45,ha='right')
   

fig.suptitle('ses-MPN1Scan1_task-cloudy_echo-1_bold', fontsize=16)
#plt.tight_layout(rect=[0, 0.03, 1, 0.95])     
plt.tight_layout()
plt.show()

# Here should superimpose participant # Now Hardwired should be part of python wrapper with args. (POP_input_BOLD, PNT_input_BOLD_OUTPUT)


# OTHER ## Probably iterate through group of vars, AND process input in wrapper ### CBRAIN?
variables = ['aor','aqi','fd_perc','fd_num','fd_mean','summary_bg_mean']
FDF = df_melted[df_melted["IQM"].isin(variables)]




